// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokVjfze4aTyoygtmJrUPsTb40_aTijAI',
    appId: '1:467512389115:web:8610f60d14f65d6e272f5e',
    messagingSenderId: '467512389115',
    projectId: 'bloom-and-bunch-kl',
    authDomain: 'bloom-and-bunch-kl.firebaseapp.com',
    storageBucket: 'bloom-and-bunch-kl.firebasestorage.app',
    measurementId: 'G-BWYMRP6V5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIHGhP1h_oNNN4qjDbdzx8UbHxM8lYww',
    appId: '1:467512389115:android:58a843b318815641272f5e',
    messagingSenderId: '467512389115',
    projectId: 'bloom-and-bunch-kl',
    storageBucket: 'bloom-and-bunch-kl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmZXcMjLpb6K0COhEDn6YQj3KwwPqHRQ',
    appId: '1:467512389115:ios:afb69b0d1a9299df272f5e',
    messagingSenderId: '467512389115',
    projectId: 'bloom-and-bunch-kl',
    storageBucket: 'bloom-and-bunch-kl.firebasestorage.app',
    iosBundleId: 'com.example.bloomAndBunchKl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkmZXcMjLpb6K0COhEDn6YQj3KwwPqHRQ',
    appId: '1:467512389115:ios:afb69b0d1a9299df272f5e',
    messagingSenderId: '467512389115',
    projectId: 'bloom-and-bunch-kl',
    storageBucket: 'bloom-and-bunch-kl.firebasestorage.app',
    iosBundleId: 'com.example.bloomAndBunchKl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDokVjfze4aTyoygtmJrUPsTb40_aTijAI',
    appId: '1:467512389115:web:ffc76626fad25409272f5e',
    messagingSenderId: '467512389115',
    projectId: 'bloom-and-bunch-kl',
    authDomain: 'bloom-and-bunch-kl.firebaseapp.com',
    storageBucket: 'bloom-and-bunch-kl.firebasestorage.app',
    measurementId: 'G-K8WZ63K4MS',
  );
}
